// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiHSYhXwWAXQaKZr7xod_3gplTPLaNaGs',
    appId: '1:321420766532:web:4fcf0291718104cfb5fb11',
    messagingSenderId: '321420766532',
    projectId: 'ecotrack-2f934',
    authDomain: 'ecotrack-2f934.firebaseapp.com',
    storageBucket: 'ecotrack-2f934.appspot.com',
    measurementId: 'G-8C38XWQW8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLhjantuuuR7mmj0edkJkITKF6Y7G2m1M',
    appId: '1:321420766532:android:7daa44c7c6596937b5fb11',
    messagingSenderId: '321420766532',
    projectId: 'ecotrack-2f934',
    storageBucket: 'ecotrack-2f934.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJCQOgnM2xfp2YGZ8adOZqqFxxex2rAMo',
    appId: '1:321420766532:ios:2825f074d973e122b5fb11',
    messagingSenderId: '321420766532',
    projectId: 'ecotrack-2f934',
    storageBucket: 'ecotrack-2f934.appspot.com',
    iosBundleId: 'com.example.carbonFootprintTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJCQOgnM2xfp2YGZ8adOZqqFxxex2rAMo',
    appId: '1:321420766532:ios:3804a809993158b2b5fb11',
    messagingSenderId: '321420766532',
    projectId: 'ecotrack-2f934',
    storageBucket: 'ecotrack-2f934.appspot.com',
    iosBundleId: 'com.example.carbonFootprintTracker.RunnerTests',
  );
}
